dist: bionic
os: linux
language: bash

env:
  global:
    - IMAGE=drpsychick/signal-demo
    - UBUNTU_VERSION=latest

script:
  # first run, stop through signal
  - docker build --build-arg UBUNTU_VERSION=$UBUNTU_VERSION -t $IMAGE .
  - docker run -d --name demo1 $IMAGE
  - sleep 2
  - docker exec demo1 kill -HUP 1
  - docker exec demo1 kill -INT 1
  - docker logs -f demo1
  # second run, stop through docker
  - docker run -d --name demo2 $IMAGE
  - sleep 2
  - docker exec demo2 kill -USR1 1
  - sleep 2
  - docker stop demo2
  - docker logs -f demo2
  # third run, stop exec
  - docker run -d --name demo3 -e EXEC_DEMO=yes $IMAGE
  - docker logs -f demo3


after_success:
  - bash deploy.sh